### PR TITLE
Okan fix right biceps

### PR DESCRIPTION
**Pull request by el-tomo**
fixed problem w/ right biceps example

### CODE REVIEW

**Comment by chrispbradley** [comment]
@el-tomo you probably need to commit this to the cm repository as well as we haven't switched over to this repository yet.

**Comment by rondiplomatico** [comment]
gojenkins

**Comment by ghost** [comment]
Admins: Please verify! Reply with

```
"ok to test" to accept this pull request for testing
"test this please" for a one time test run
"add to whitelist" to add the author to the whitelist
```

**Comment by rondiplomatico** [comment]
ok to test

**Pull request merged**
