### PR TITLE
Revert "3D-0D fluid coupling"

### PR DESCRIPTION
**Pull request by hsorby**
Reverts OpenCMISS/iron#72.

Still a few items on the TODO list to be done before this should be merged.

### CODE REVIEW

**Comment by chrispbradley** [comment]
What todo list? Why are you reverting? I'm explicitly getting this in.

**Comment by nickerso** [comment]
@dladd had added a todo list on the original pull request (#72) that looked like it was still work to be completed before the code was ready for review (copied below for convenience). If there is some reason for those todo's not to be done before review and merging, then a comment stating this should be made so that the team knows why apparently incomplete code is being merged in.

Is that any clearer?

TODO:

- [ ]  Boundary element face integration
  - [ ]  Generalise boundary line/face integration to 2D/3D (currently 3D faces only)
  - [ ]  Generalise for simplex element types
- [ ]  Remove legacy/nonfunctioning 3D-1D code
- [ ]  Re-work/generalise hard-coded fix calling CellML solver at each residual evaluation (see changes to problem_routines.)

**Comment by chrispbradley** [comment]
These TODO's are future enhancements. They should be put as an issue. They do not prevent this being pulled in.

**Comment by nickerso** [comment]
I agree, future enhancements should be new issues and not listed as TODO's on a pull request.

**Comment by hsorby** [comment]
There is also the comment:

I still have a bit of tidy-up to do but thought I should get the pull request going to track this.

that clearly states that this is the start of the pull request, as the developer documentation says start the pull request so people can see what is happening.

**Comment by chrispbradley** [comment]
I am explicitly allowing this and pulling this in. David, can you please make another pull request.

**Comment by dladd** [comment]
I am now seeing: 

OpenCMISS:develop is up to date with all commits from dladd:dladd_phd. Try switching the base for your comparison.

when I try to start another pull request (I just opened and closed one that accidentally targeted devel rather than develop). It appears since this was merged then reverted that it won't let me start the same pull?

**Comment by hsorby** [comment]
This is possibly a feature of GitHub.  From what I can tell it is probably easiest for @chrispbradley to manually merge the code.   I am not convinced that adding a new commit and creating another pull request will work.

**Comment by dladd** [comment]
Yes I saw a StackOverflow thread that mentioned re-pulling after new commits being a possibility. I'll try to knock out those TODO's and see if it works after that. Otherwise, will try a more manual approach per your recommendation.

**Pull request merged**
