### PR TITLE
Wrap dependency detection for static builds only.

### PR DESCRIPTION
**Pull request by hsorby**
This pull request is being used to test the Jenkins testing mechanism, please ignore for the moment.

### CODE REVIEW

**Comment by hsorby** [comment]
ok to test.

**Comment by hsorby** [comment]
add to whitelist

**Comment by hsorby** [comment]
add to whitelist.

**Comment by hsorby** [comment]
add to whitelist.

**Comment by hsorby** [comment]
add to whitelist.

**Comment by abi-git-user** [comment]
Testing posting to PR.

**Comment by hsorby** [comment]
add to whitelist.

**Comment by hsorby** [comment]
ok to test.

**Comment by hsorby** [comment]
ok to test.

**Pull request merged**
